### ISSUE TITLE
ERS-013 After the second round of messaging evaluation, the "next dater" button on messaging evaluation survey doesn't work for any dater

### ISSUE THREAD

**Issue by dougzytko** [markovLabs/eros#18]
Only half of the daters can progress to the second round of conversation, but none of those can progress to the third round. The "next dater" button on the messaging evaluation survey doesn't work. No dater was able to progress to the third conversation.

**Comment by vrrs** [comment]
The issue was that matches with prompted stories was not displaying first question but the form submitted by the next dater button assumed that the user was just not choosing an answer and hence was not proceeding. Fixed and deploy. Closing...
