### ISSUE TITLE
ERS-017 Formatting and statement changes

### ISSUE THREAD

**Issue by dougzytko** [markovLabs/eros#32]
PROFILE PAGE
—put words on +/- buttons
—put instructions at top of page to add two pictures

EVENT PAGE
—add Doug’s contact info or mention that you’ll receive an e-mail from me
—remind the user about refund and payment, be on time

MESSAGING INTERFACE
—in prompted with agreement > “YOU both picked” instead of just “both picked”
—take first two sentences off unprompted instructions

MESSAGING EVALUATION SURVEY
—Answer the following question…” should say “questions”

**Comment by vrrs** [comment]
Deployed
