### ISSUE TITLE
ERS-039 new messages do not appear in messaging interface

### ISSUE THREAD

**Issue by dougzytko** [markovLabs/eros#71]
For some users at the event, new messages from the dater they were talking to wouldn't show up unless they manually refreshed the page. I'm not sure what was triggering this, but when I tested Tuesday morning one scenario that caused the issue was this: if user A sends a message to user B before user B got to the messaging screen (e.g. if they were still taking the previous survey).

**Comment by vrrs** [comment]
Closing... Create new issue if something happen again.
